- name: Install Docker and Deploy Application
  hosts: all
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name: 
          - docker.io
          - docker-compose
        state: present

    - name: Clone the application repository
      git:
        repo: "https://github.com/YOUR_GITHUB_USERNAME/DevOps-Stage-4.git"
        dest: "/home/ubuntu/todo-app"

    - name: Deploy the application
      shell: "cd /home/ubuntu/todo-app && docker-compose up -d"
